accounts/urls.py
from django.urls import path, include

from .views import LoggedOutView, UserDetailView, UserListView

urlpatterns = [
    path("", include("allauth.urls")),
    path("loggedout/", LoggedOutView.as_view(), name="logged_out"),
    path("users/list/", UserListView.as_view(), name="user_list"),
    path("users/<uuid:pk>/", UserDetailView.as_view(), name="user_detail"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls")),
    path("accounts/", include("accounts.urls")),
    path("tinymc/", include("tinymce.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path

from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
)

app_name = "posts"

urlpatterns = [
    path("", PostListView.as_view(), name="post_list"),
    path("post/create/", PostCreateView.as_view(), name="post_create"),
    path("post/<slug:slug>/", PostDetailView.as_view(), name="post_detail"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

import uuid


class AuthorUsers(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(posts__isnull=False)


class CustomUser(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    bio = models.TextField(verbose_name=_("biography"), blank=True, null=True)

    objects = UserManager()
    authors = AuthorUsers()

    def get_absolute_url(self):
        return reverse("user_detail", args=[self.id])

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from tinymce.models import HTMLField


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class PostCategory(models.Model):
    category = models.CharField(_("category"), max_length=50)

    class Meta:
        verbose_name = _("category")
        verbose_name_plural = _("categories")

    def __str__(self):
        return self.category


class Tag(models.Model):
    tag = models.CharField(_("tag"), max_length=50)

    class Meta:
        verbose_name = _("tag")
        verbose_name_plural = _("tags")

    def __str__(self):
        return self.tag


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Publish"

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="posts"
    )
    title = models.CharField(_("title"), max_length=100)
    slug = models.SlugField(max_length=250, unique=True)
    content = HTMLField(verbose_name=_("content"))
    categories = models.ManyToManyField(PostCategory, related_name="posts")
    tags = models.ManyToManyField(Tag, related_name="posts")
    publish = models.DateTimeField(verbose_name=_("published at"), default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=Status.choices, default=Status.DRAFT
    )
    hits = models.PositiveIntegerField(verbose_name="view", default=0)

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        verbose_name = _("post")
        verbose_name_plural = _("posts")

        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"]),
        ]

    def get_absolute_url(self):
        return reverse("posts:post_detail", args=[self.slug])

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    comment = models.CharField(max_length=255)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    publish = models.DateTimeField(verbose_name=_("published at"), default=timezone.now)

    def get_absolute_url(self):
        return reverse("posts:post_list")

    def __str__(self):
        return self.comment

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
        )

posts/forms.py
from django import forms

from tinymce.widgets import TinyMCE

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "slug", "author", "content", "categories", "tags", "status"]
        widgets = {"content": TinyMCE(attrs={"class": "edit_by_tinemce"})}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("comment",)
        # widgets = {"comment": TinyMCE(attrs={"class": "edit_by_tinemce"})}

accounts/views.py
from django.contrib.auth.views import LogoutView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import CustomUser


class LoggedOutView(LogoutView):
    template_name = "account/logged_out.html"


class UserDetailView(DetailView):
    model = CustomUser
    template_name = "users/user_detail.html"


class UserListView(ListView):
    model = CustomUser
    template_name = "users/user_list.html"
    context_object_name = "user_list"

    def get_queryset(self):
        return CustomUser.authors.all()

posts/views.py
import random

from django.views.generic.list import ListView, View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template.defaultfilters import slugify
from django.views.generic.detail import SingleObjectMixin
from django.urls import reverse

from .models import Post, Comment
from .forms import CommentForm


class CommentGet(DetailView):
    model = Post
    template_name = "posts/post_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CommentForm()
        return context


class CommentPost(SingleObjectMixin, FormView):
    model = Post
    form_class = CommentForm
    template_name = "posts/post_detail.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = self.object
        form.instance.author = self.request.user
        comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        article = self.get_object()
        return reverse("posts:post_detail", kwargs={"slug": article.slug})


class PostDetailView(DetailView):
    model = Post
    template_name = "posts/post_detail.html"

    def get(self, request, *args, **kwargs):
        view = CommentGet.as_view()
        self.get_object().hits += 1
        self.get_object().save()
        # return super().get(request, *args, **kwargs)  # + view(request, *args, **kwargs)
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = CommentPost.as_view()
        return view(request, *args, **kwargs)


class PostListView(ListView):
    model = Post
    template_name = "posts/post_list.html"
    paginate_by = 5

    def get_queryset(self):
        return Post.published.all()


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = (
        "title",
        "content",
        "categories",
        "tags",
        "status",
    )
    template_name = "posts/post_create.html"

    def new_slug(self, slug):
        slug = slug + str(random.randint(1, 10**6))
        return slug

    def make_slug(self, slug):
        post = Post.objects.filter(slug=slug)
        if post.exists():
            slug = self.new_slug(slug)
            return self.make_slug(slug)

        return slug

    def form_valid(self, form):
        form.instance.author = self.request.user
        slug = slugify(self.request.POST.get("title"))
        form.instance.slug = self.make_slug(slug)

        return super().form_valid(form)

templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}my site{% endblock %}</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>

<body>
  <header>
    <h4><a href="{% url 'posts:post_list' %}">my site</a></h4>
    {% if user.is_authenticated %}
      <p>{{ user.username }}</p>
      <p><a href="{% url 'account_logout' %}">Log Out</a></p>
      <p><a href="{% url 'posts:post_create' %}">New Post</a></p>
    {% else %}
      <p><a href="{% url 'account_login' %}">Log In</a></p>
      <p><a href="{% url 'account_signup' %}">Sign Up</a></p>
    {% endif %}
    <p><a href="{% url 'user_list' %}">Users</a></p>

    <hr>
    <hr>
    
  </header>
  {% block content %}

  {% endblock content %}
</body>

</html>

templates/home.html
{% extends '_base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
	<h1>Home page</h1>
{% endblock %}

templates/posts/post_create.html
{% extends "_base.html" %}

{% block title %}New Post{% endblock %}

{% block content %}
	<h2>New Post</h2>
  <form method="post" action="">{% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success ml-2" type="submit">Save</button>
  </form>
{% endblock %}

templates/posts/post_detail.html
{% extends "_base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
	<h2>{{ post.title }}</h2>
  <p><small>{% for cat in post.categories.all %}<a href="#">{{ cat }}</a> {% endfor %}</small></p>
  <p>by: <em><a href="{{ post.author.get_absolute_url }}">{{ post.author }}</a></em></p>
  <p>{{ post.content|safe }}</p>
  <p><small>published: {{ post.publish|date:"Y/m/d" }}</small></p>
  <p><small>tags: {% for tag in post.tags.all %}<a href="#">{{ tag }}</a> {% endfor %}</small></p>

  <hr>
  <h5>comments</h5>
  {% for comment in post.comments.all %}
  	<p>{{ comment.author }} &middot; {{ comment }}</p>
  {% endfor %}
  <hr>

  <h4>add a new comment</h4>
  <form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success ml-2" type="submit">Save</button>
  </form>
{% endblock %}

templates/posts/post_list.html
{% extends "_base.html" %}

{% block title %}posts{% endblock %}

{% block content %}
	<h1>Posts</h1>

  {% for post in post_list %}
    <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
    <p>{{ post.content | safe }}</p>
    <p><a href="{{ post.author.get_absolute_url }}">{{ post.author }}</a></p>
    <p>{% for tag in post.tags.all %}<a href="#">{{ tag }}</a> {% endfor %}</p>
    <p>created at: {{ post.created }}</p>
    <p>categories: {% for cat in post.categories.all %}<a href="#">{{ cat }}</a> {% endfor %}</p>
    <hr>
  {% endfor %}

{% endblock %}

templates/users/user_detail.html
{% extends "_base.html" %}

{% block title %}{{ customuser.username }}{% endblock %}

{% block content %}
	<h2>{{ customuser.username }}</h2>

  {% if customuser.bio %}
    <p>{{ customuser.bio }}</p>
  {% endif %}
  <hr>

  {% for post in customuser.posts.all %}

    <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
    {{ post.content|safe|truncatewords:15|linebreaks }}
    <p><small>published: {{ post.publish|date:"Y/m/d" }}</small></p>
  	<hr>

  {% endfor %}

{% endblock %}

templates/users/user_list.html
{% extends "_base.html" %}

{% block title %}Users{% endblock %}

{% block content %}
	{% for user in user_list %}
    <p><a href="{{ user.get_absolute_url }}">{{ user.username }}</a></p>
    <hr>
	{% endfor %}

{% endblock %}